export const MATCH_BORDER_DRAW_MS = 950;
export const MATCH_BORDER_HOLD_MS = 260;
export const MATCH_COLLECT_DELAY_MS = MATCH_BORDER_DRAW_MS + MATCH_BORDER_HOLD_MS;
export const MISMATCH_FLIP_DELAY_MS = 700;
export const CARD_FLY_DURATION_MS = 760;
export const STACK_PILE_CARD_LIMIT = 16;
export const SCREEN_LEAVE_ANIMATION_MS = 260;
export const WINNER_CONTINUE_UNLOCK_MS = 2000;
export const WINNER_AUTO_ADVANCE_MS = 10000;
export const WINNER_FLOW_INIT_DELAY_MS = SCREEN_LEAVE_ANIMATION_MS + 40;

export const WINNER_ASSET_THEME = "code-vibes";

